import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.scss';
import ProposalListItem from '../components/ProposalListItem';

const Home: NextPage = () => {
  return (
    <Layout home>
      <Head>
        <title>Superlative DAO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <section className={styles.ProposalList}>
          <ProposalListItem
            title='Do you like art'
            datePosted='05/05/2021'
            authorId='0x4e0843e8daa53406121588feebf0cde0f1fcefc1'
            id='s1'
            status='open'
            description='To determine how much you like the art.'
          />
          <ProposalListItem
            title='Which should comes first?'
            datePosted='08/25/2021'
            authorId='0x4e0843e8daa53406121588feebf0cde0f1fcefc1'
            id='s2'
            status='open'
          />
        </section>
      </main>
    </Layout>
  );
};

export default Home;
